### ISSUE TITLE
TEST: Error Could not fetch current balance shown when user has ETH on balance

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#1]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x34570e77d64775da89ec4d9b9450d0cb0502a2cf1ab76852d80c07f3565c00fb](https://ropsten.etherscan.io/tx/0x34570e77d64775da89ec4d9b9450d0cb0502a2cf1ab76852d80c07f3565c00fb)
