### ISSUE TITLE
TEST2: comment after merge is not updated

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#10]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x9fefe6ed30206da6517aa311722221f2b2ce389239c0f5469542e4c62418c54b](https://ropsten.etherscan.io/tx/0x9fefe6ed30206da6517aa311722221f2b2ce389239c0f5469542e4c62418c54b)
