### ISSUE TITLE
TEST4: Fix me  and add PR comment later

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#13]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x8eac3d66c2fe4caa66f670fd65822db9ed972ec4b7c542382b2b118fd9ecbaf0](https://ropsten.etherscan.io/tx/0x8eac3d66c2fe4caa66f670fd65822db9ed972ec4b7c542382b2b118fd9ecbaf0)
