### ISSUE TITLE
Multiple check

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#15]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x80fcdf61a0133125a50a96e301e42f55199df06decc527532630e6977686ec5d](https://ropsten.etherscan.io/tx/0x80fcdf61a0133125a50a96e301e42f55199df06decc527532630e6977686ec5d)
