### ISSUE TITLE
TEST6: recheck bounty is paid

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#18]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x526cc2eefc290e2ea18b53c9e57ee24714c30bba8ab16c8396347942c1cb040d](https://ropsten.etherscan.io/tx/0x526cc2eefc290e2ea18b53c9e57ee24714c30bba8ab16c8396347942c1cb040d)
