### ISSUE TITLE
TEST: second

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#2]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xc80c4ee273f51aae2a931cdf6b0828cc4f43b1da0eadf90dbb16fe011264fa01](https://ropsten.etherscan.io/tx/0xc80c4ee273f51aae2a931cdf6b0828cc4f43b1da0eadf90dbb16fe011264fa01)
