### ISSUE TITLE
Recheck multi 1507

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#21]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x14cd05bf97e4587544d120155479e9009417ae75636cc66e38eb7bcade5c0ea2](https://ropsten.etherscan.io/tx/0x14cd05bf97e4587544d120155479e9009417ae75636cc66e38eb7bcade5c0ea2)
