### ISSUE TITLE
MULTI3

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#23]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x54e4404548f4e00c083207457673d5f327c47dd659c5de8dea4126ce999c77d2](https://ropsten.etherscan.io/tx/0x54e4404548f4e00c083207457673d5f327c47dd659c5de8dea4126ce999c77d2)
