### ISSUE TITLE
TESTNOV2: Multiple check again

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#24]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x7426809775ad78d4f0b0317b9d0d923d8365f3f6f3581464dcb0a1dac56b228e](https://ropsten.etherscan.io/tx/0x7426809775ad78d4f0b0317b9d0d923d8365f3f6f3581464dcb0a1dac56b228e)
