### ISSUE TITLE
Check new winner

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#25]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xd9cee2b701b2c49842f68fa54457792b95a324295c5d5fc26e09f831e2226faa](https://ropsten.etherscan.io/tx/0xd9cee2b701b2c49842f68fa54457792b95a324295c5d5fc26e09f831e2226faa)
