### ISSUE TITLE
TEST: 3rd issue should not get bounties

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#3]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x373a5b7e5ae90966706fa748d771db34981d788d1b51cee6dc67be385f747b30](https://ropsten.etherscan.io/tx/0x373a5b7e5ae90966706fa748d771db34981d788d1b51cee6dc67be385f747b30)
