### ISSUE TITLE
Forget comment

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#42]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xba83ee606ac19b27c59cd4563ba8fa4f3b544f14a6845c6f1733d08b6f29012d](https://ropsten.etherscan.io/tx/0xba83ee606ac19b27c59cd4563ba8fa4f3b544f14a6845c6f1733d08b6f29012d)
