### ISSUE TITLE
fixed by c4

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#48]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x40fa306c0987c12b0b9b4e8d1dff54097ad8a62a32a1470553f0e2e35e2fa0a5](https://ropsten.etherscan.io/tx/0x40fa306c0987c12b0b9b4e8d1dff54097ad8a62a32a1470553f0e2e35e2fa0a5)
