### ISSUE TITLE
Initial to claim

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#49]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xdedfe240341bb1b32155ba80a7a11ba57c1e7c7c7015993ac0ce7889de9cd736](https://ropsten.etherscan.io/tx/0xdedfe240341bb1b32155ba80a7a11ba57c1e7c7c7015993ac0ce7889de9cd736)
