### ISSUE TITLE
Changed issue to claim in edit

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#50]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xa8d7f30222503c5bef88f19e7e7e8150a351fcf48ba0b95b4e5de4206b90eb77](https://ropsten.etherscan.io/tx/0xa8d7f30222503c5bef88f19e7e7e8150a351fcf48ba0b95b4e5de4206b90eb77)
