### ISSUE TITLE
TEST1: THis should be closed and bounty paid

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#6]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x2e341afcd2d98cf76188a3eacaf09290eb23c0ee3ff07c4664a90f23f4dd66ea](https://ropsten.etherscan.io/tx/0x2e341afcd2d98cf76188a3eacaf09290eb23c0ee3ff07c4664a90f23f4dd66ea)
