### ISSUE TITLE
Closed to check reference to closed issue

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#63]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x07756ce17e25b1c2562e982bd649f94d036666726645e22d447fcbb844056e51](https://ropsten.etherscan.io/tx/0x07756ce17e25b1c2562e982bd649f94d036666726645e22d447fcbb844056e51)
