### ISSUE TITLE
c8: commit message

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#70]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xceb1518da00911b87b9c02561ac3ef49589bf6e777e38ad351198b6798c8ad05](https://ropsten.etherscan.io/tx/0xceb1518da00911b87b9c02561ac3ef49589bf6e777e38ad351198b6798c8ad05)
