### ISSUE TITLE
MUL1: Anna 2nd PR, Anna wins

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#83]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Contract address: [0xc0e843ff98839af97cf44cc82b09e6eb354d088c](https://ropsten.etherscan.io/address/0xc0e843ff98839af97cf44cc82b09e6eb354d088c)
Network: Testnet (Ropsten)
Paid to: antdanchenko
