### ISSUE TITLE
MUL3: Anna 1st PR, Anton wins

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#85]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xbcfbce041416229ec5dfe39b8e4a7a7f4c1fe32ebe12e2fed7451482a35b2091](https://ropsten.etherscan.io/tx/0xbcfbce041416229ec5dfe39b8e4a7a7f4c1fe32ebe12e2fed7451482a35b2091)
