### ISSUE TITLE
Reopen test1105

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#9]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x6d78066e02ea04b21bea5462751259c39f84e19783c4588653f90bc6a806d3bd](https://ropsten.etherscan.io/tx/0x6d78066e02ea04b21bea5462751259c39f84e19783c4588653f90bc6a806d3bd)

**Comment by anna04test** [comment]
closed

**Comment by anna04test** [comment]
reopened
